DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS article;

CREATE TABLE article (
articleId INT UNSIGNED AUTO_INCREMENT NOT NULL,
articleDate DATETIME NOT NULL,
issueId VARCHAR(32)NOT NULL,
articleContent MEDIUMTEXT NOT NULL,
PRIMARY KEY (articleId)
);
CREATE TABLE tag (
tagId VARCHAR(32) NOT NULL,
tagName VARCHAR(32),
articleId INT UNSIGNED AUTO_INCREMENT NOT NULL,
INDEX (articleId),
FOREIGN KEY (articleId)REFERENCES article(articleId),
PRIMARY KEY (tagId)
);
